navigation_weight:
  Messaging: 1
  SMS: 1
  Voice: 2
  Verify: 3
  Number Insight: 4
  Messages and Workflows: 5
  Account: 99
  Concepts: 0

  Overview: 1
  Developer Preview: 2
  Quickstarts: 3
  Guides: 4
  Building Blocks: 5

  Tutorials: 6
  API Reference: 7
  Conversation: 8

  Voice API: 1
  SIP: 2

  Client SDKs: 30
  NCCO Reference: 40
  SDK Documentation: 40
  API Reference: 50

  Overview: 1
  Concepts: 2
  In-App Messaging: 3
  In-App Voice: 4
  In-App Video: 5

  Messages API: 1
  Workflows API: 2

navigation_overrides:
  concepts:
    svg: 'mind-map'
    svgColor: 'red'
  messaging:
    svg: 'message'
    svgColor: 'purple'
  voice:
    svg: 'phone'
    svgColor: 'green'
    voice-api:
      guides:
        lex-connector:
          label: 'DP'
  verify:
    svg: 'chat'
    svgColor: 'indigo'
  number-insight:
    svg: 'file-search'
    svgColor: 'orange'
  account:
    svg: 'user'
    svgColor: 'blue'
  redact:
    label: 'DP'
    svg: 'lock'
    svgColor: 'red'
  stitch:
    svg: 'duplicate'
    svgColor: 'teal'
    label: 'DP'
    sdk-documentation:
      link: false
      prevent_navigation_item_class: true
  messages-and-workflows-apis:
    svg: 'message'
    svgColor: 'purple'
    messages:
      label: 'DP'
    workflows:
      label: 'DP'
